source "docker" "autogenerated_1" {
  discard = true
  image   = "ubuntu"
}

build {
  sources = ["source.docker.autogenerated_1"]

  provisioner "shell" {
    inline = ["dd if=/dev/urandom of=/tmp/cupcake bs=1M count=2", "dd if=/dev/urandom of=/tmp/bigcake bs=1M count=100", "sync", "md5sum /tmp/cupcake /tmp/bigcake"]
  }

  provisioner "file" {
    destination = "cupcake"
    direction   = "download"
    source      = "/tmp/cupcake"
  }

  provisioner "file" {
    destination = "bigcake"
    direction   = "download"
    source      = "/tmp/bigcake"
  }

}
