# Copyright IBM Corp. 2013, 2025
# SPDX-License-Identifier: MPL-2.0


source "docker" "autogenerated_1" {
  discard     = true
  image       = "ubuntu"
  run_command = ["-d", "-i", "-t", "{{ .Image }}", "/bin/sh"]
}

build {
  sources = ["source.docker.autogenerated_1"]

  provisioner "file" {
    destination = "/strawberry-cake"
    source      = "test-fixtures/onecakes/strawberry"
  }

  provisioner "file" {
    destination = "my-strawberry-cake"
    direction   = "download"
    source      = "/strawberry-cake"
  }

}
