name: Notify Integration Release (Manual)
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version (semver)"
        default: 0.0.1
        required: false
      branch:
        description: "A branch or SHA"
        default: 'main'
        required: false
jobs:
  strip-version:
    runs-on: ubuntu-latest
    outputs:
      packer-version: ${{ steps.strip.outputs.packer-version }}
    steps:
      - name: Strip leading v from version tag
        id: strip
        env:
          REF: ${{ github.event.inputs.version }}
        run: |
          echo "packer-version=$(echo "$REF" | sed -E 's/v?([0-9]+\.[0-9]+\.[0-9]+)/\1/')" >> "$GITHUB_OUTPUT"
  notify-release:
    needs:
      - strip-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          ref: ${{ github.event.inputs.branch }}
      # Ensure that Docs are Compiled
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      - shell: bash
        run: make generate
      - shell: bash
        run: |
          uncommitted="$(git status -s)"
          if [[ -z "$uncommitted" ]]; then
            echo "OK"
          else
            echo "Docs have been updated, but the compiled docs have not been committed."
            echo "Run 'make generate', and commit the result to resolve this error."
            echo "Generated but uncommitted files:"
            echo "$uncommitted"
            exit 1
          fi
      # Perform the Release
      - name: Checkout integration-release-action
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: hashicorp/integration-release-action
          path: ./integration-release-action
      - name: Notify Release
        uses: ./integration-release-action
        with:
          integration_identifier: "packer/hashicorp/docker"
          release_version: ${{ needs.strip-version.outputs.packer-version }}
          release_sha: ${{ github.event.inputs.branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
